# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: ubuntu/postgres
    restart: always

    environment:
      POSTGRES_USER: aplicacao
      POSTGRES_PASSWORD: 12345pasta
      POSTGRES_DB: Cardapio
      POSTGRES_HOST_AUTH_METHOD: trust

    ports:
      - 5432:5432
      - 422:22
      - 3080:80

  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080
